### ISSUE TITLE
Sets not downloading from Scryfall

### ISSUE THREAD

**Issue by c-dot-gonz** [ForOhForError/Yet-Another-Magic-Card-Recognizer#1]
Hello! I've been trying to get the source files and the previous release (0.03) to work on my machine, but the sets will not download from Scryfall. When attempting to compile the source code in Eclipse, I get the following exception:

Exception in thread "main" java.lang.NullPointerException
	at forohfor.scryfall.api.Card.<init>(Card.java:84)
	at forohfor.scryfall.api.MTGCardQuery.getCardByScryfallId(MTGCardQuery.java:141)
	at ThresholdTester.main(ThresholdTester.java:30)

When inspecting the individual class files above, Eclipse says that 84 and 141 are not valid line numbers for their respective files, and only points me to the following bit of code: 				MTGCardQuery.getCardByScryfallId("51f724db-0427-44f9-963d-ae2356c928f4").getCannonicalImage());

I'm not familiar with java and have not had any luck yet trying to solve this particular issue on my own, so any help would be appreciated. If it would be possible for me to download images from Scryfall and generate the data sets that way, please let me know. In the meantime, I will keep trying to solve this issue on my own.

**Comment by ForOhForError** [comment]
Looks like scryfall probably updated their API since I last maintained this, I need to update the Scryfall API bindings to work properly.

**Comment by ForOhForError** [comment]
Fixed with latest release

**Comment by c-dot-gonz** [comment]
Thank you so much for the quick fix! I will test it out when I get home.

Is there any way to adapt the code for use with custom sets of images (for things like custom MTG sets like Aenyr or Star Wars The Gathering)? Or is it reliant on Scryfall for Multiverse IDs?

**Comment by c-dot-gonz** [comment]
I tested it and it works! Thank you again for updating the API bindings so quickly!

**Comment by c-dot-gonz** [comment]
Alrighty. Regarding the deck list feature, is it like your DeckedBuilder tool where you can put either Multiverse ID or the name and it will generate the card file? I haven't gotten to test that just yet, but I will give it a shot later tonight before the prerelease.

**Comment by ForOhForError** [comment]
Only card name at the moment. If you have any issues def let me know, that feature isn't super far along.

**Comment by c-dot-gonz** [comment]
Roger. I will keep you posted when I try it.

Regarding the card reader, it does not like split cards like Integrity//Intervention. I have to set the threshold very low just for it to even start generating cards, and at that point, they are nowhere near the card. Lighting, angle, rotation, and anything else I've tried will not adjust it. =
