### ISSUE TITLE
Export Detected Cards

### ISSUE THREAD

**Issue by wwwood** [ForOhForError/Yet-Another-Magic-Card-Recognizer#2]
Hello,
First, I want to say that your software is awesome. I appreciate all the work you've put into making this.
Is there any functionality that would allow me to export the detected cards in some way? As in, I scan "Medomai's Prophecy" from THB, YAMCR correctly recognizes it, and then saves it to a list? I'm not a developer by any means but I'm a decent sysadmin, if there's a file somewhere that contains the current card's scryfall ID I can hack something together with that.
Thanks again.

**Comment by ForOhForError** [comment]
Right now, this feature isn't implemented -- I intend to add a collection feature in the coming weeks that should address this.

**Comment by wwwood** [comment]
Awesome. Looking forward to it.

**Comment by ForOhForError** [comment]
Released in 0.1.1
